//  Created by TagCommander on 29/01/2021.
//  Version : 4.6.15
//
//  Copyright (c) 2021 Commanders Act. All rights reserved.
//
// THIS IS A GENERATED FILE. DO NOT EDIT THIS FILE BY HAND.

#ifndef __PRIVACY_GENERATED_H__
#define __PRIVACY_GENERATED_H__

#import <Foundation/Foundation.h>

extern NSString *const kTCPrivacyVersion;

extern NSString *const kTCReleaseDate;
extern NSString *const kTCReleaseTime;

#define TC_USE_IDFA
#define TC_USE_IAB

#endif //__PRIVACY_GENERATED_H__
