//  Created by TagCommander on 22/05/2019.
//  Version : 4.3.2
//
//  Copyright (c) 2019 Commanders Act. All rights reserved.
//
// THIS IS A GENERATED FILE. DO NOT EDIT THIS FILE BY HAND.

#ifndef __CORE_GENERATED_H__
#define __CORE_GENERATED_H__

#import <Foundation/Foundation.h>

extern NSString *const kTCCoreVersion;

extern NSString *const kTCReleaseDate;
extern NSString *const kTCReleaseTime;

#define TC_USE_IDFA

#endif //__CORE_GENERATED_H__
