//  Created by TagCommander on 19/04/2021.
//  Version : 4.7.6
//
//  Copyright (c) 2021 Commanders Act. All rights reserved.
//
// THIS IS A GENERATED FILE. DO NOT EDIT THIS FILE BY HAND.

#ifndef __CORE_GENERATED_H__
#define __CORE_GENERATED_H__

#import <Foundation/Foundation.h>

extern NSString *const kTCCoreVersion;

extern NSString *const kTCReleaseDate;
extern NSString *const kTCReleaseTime;




#endif //__CORE_GENERATED_H__
